### PR TITLE
replace sbrk with mbed_sbrk in the definition of MORECORE.

### PR DESCRIPTION
**Pull request by rgrover**
CR @0xc0170 @bremoran @bogdanm

### CODE REVIEW

**Comment by 0xc0170** [comment]
LTGM.

Is this the last fix for our latest armcc targets compilation problems?

**Comment by rgrover** [comment]
no, i'll also need a proper solution to the LDREX/STREX issue.

**Comment by bremoran** [comment]
+1

**Comment by rgrover** [comment]
@bremoran could you please create a new patch version and push this change? Else I'm happy to do this if you give me push rights.

**Comment by bremoran** [comment]
Added

**Pull request merged**
